BookStore1/Controllers/AuthorController.cs
using BookStore1.Data;
using BookStore1.Models;
using BookStore1.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore1.Controllers
{
    public class AuthorController : Controller
    {
        private IConfiguration Configuration;
        IAuthorService authorService;
        INationality nationalityService;

        public AuthorController(IConfiguration _configuration, IAuthorService _author, INationality _nationality)
        {
            Configuration = _configuration;
            authorService = _author;
            nationalityService = _nationality;
        }
        [Authorize]
        public IActionResult Index()
        {

            AuthorVM vm = new AuthorVM();
            vm.author = new Author();
            List<Nationality> national = nationalityService.Load();
            List<Author> author = authorService.Load();
            vm.liNationalities = national;
            vm.liAuthor = author;
            return View("AuthorPage", vm);
        }

        public IActionResult saveData(AuthorVM vm)
        {
            string path = Path.Combine(Directory.GetCurrentDirectory(), Configuration["Filepath"], vm.author.Image.FileName);
            vm.author.Image.CopyTo(new FileStream(path, FileMode.Create));
            vm.author.path = "http://localhost/bookProject1/img/" + vm.author.Image.FileName;
            List<Nationality> national = nationalityService.Load();
            authorService.Insert(vm.author);
            List<Author> author = authorService.Load();
            vm.liNationalities = national;
            vm.liAuthor = author;

            return View("AuthorPage", vm);
        }
        public IActionResult Search(AuthorVM vm)
        {
            string name = Request.Form["searchAuthor"];
            List<Author> liauthor = authorService.LoadAuthorByName(name);
            List<Nationality> national = nationalityService.Load();
            vm.liNationalities = national;
            vm.liAuthor = liauthor;
            return View("AuthorPage", vm);
        }

        // I put it in the Ajax Controller because it didn't work properly

        //public IActionResult Edit(int id)
        //{
        //    AuthorVM vm = new AuthorVM();
        //    Author author = authorService.Load(id);
        //    List<Author> liauthor = authorService.Load();
        //    List<Nationality> national = nationalityService.Load();
        //    vm.liNationalities = national;
        //    vm.liAuthor = liauthor;
        //    vm.author = author;
        //    // return View("AuthorPage", vm);
        //    return Json(vm);
        //}

        public IActionResult Update(AuthorVM vm)
        {
            authorService.Update(vm.author);
            List<Author> liauthor = authorService.Load();
            List<Nationality> national = nationalityService.Load();
            vm.liNationalities = national;
            vm.liAuthor = liauthor;
            return View("AuthorPage", vm);
        }

        public IActionResult Delete(int id)
        {
            AuthorVM vm = new AuthorVM();
            vm.author = new Author();
            List<Author> liauthor = new List<Author>();
            List<Nationality> national = nationalityService.Load();
            vm.liNationalities = national;
            vm.liAuthor = liauthor;
            authorService.Delete(id);
            return View("AuthorPage", vm);
        }
    }
}

BookStore1/Controllers/BookController.cs
using BookStore1.Data;
using BookStore1.Models;
using BookStore1.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore1.Controllers
{
    public class BookController : Controller
    {
        private IConfiguration Configuration;
        IBookService bookService;
        ICategory categoryService;
        IAuthorService authorService;
        BookContext context;

        public BookController(IConfiguration _configuration, IBookService _bookService, ICategory _categoryService, IAuthorService _authorService, BookContext _context)
        {
            Configuration = _configuration;
            bookService = _bookService;
            categoryService = _categoryService;
            authorService = _authorService;
            context = _context;
        }

        public IActionResult Index(BookVM vm)
        {
            vm.book = new Book();
            vm.author = new Author();
            vm.category = new Category();
            Category cate = new Category();
            Author auth = new Author();

            List<Book> liBook = bookService.Load();
            List<Category> liCat = categoryService.Load();
            List<Author> liAuthor = authorService.Load();
            vm.liBook = liBook;
            vm.liCategory = liCat;
            vm.liAuthor = liAuthor;
            return View("BookPage", vm);
        }


        public IActionResult saveData(BookVM vm)
        {
            string path = Path.Combine(Directory.GetCurrentDirectory(), Configuration["FilePath"], vm.book.Cover.FileName);
            vm.book.Cover.CopyTo(new FileStream(path, FileMode.Create));
            vm.book.path = "http://localhost/bookProject1/img/" + vm.book.Cover.FileName;


            List<Book> liBook = bookService.Load();
            List<Category> liCat = categoryService.Load();
            bookService.Insert(vm.book);
            List<Author> author = authorService.Load();
           
            vm.liBook = liBook;
            vm.liCategory = liCat;
            vm.liAuthor = author;
            return View("BookPage", vm);
        }

        public IActionResult Search(BookVM vm)
        {
            string name = Request.Form["searchAuthor"];
            List<Book> liBook = bookService.LoadBookByName(name);
            List<Category> liCat = categoryService.Load();
            List<Author> author = authorService.Load();
            vm.liBook = liBook;
            vm.liCategory = liCat;
            vm.liAuthor = author;
            return View("BookPage", vm);
        }

        // I put it in the Ajax Controller because it didn't work properly

        //public IActionResult Edit(int id)
        //{
        //    BookVM vm = new BookVM();
        //    Book Book = bookService.Load(id);
        //    List<Book> liBook = bookService.Load();
        //    List<Category> liCat = categoryService.Load();
        //    List<Author> author = authorService.Load();
        //    vm.liBook = liBook;
        //    vm.book = Book;
        //    vm.liCategory = liCat;
        //    vm.liAuthor = author;
        //    return Json(vm);
        //    //return View("BookPage", vm);
        //}
        public IActionResult Update(BookVM vm)
        {
            bookService.Update(vm.book);
            List<Book> liBook = bookService.Load();
            List<Category> liCat = categoryService.Load();
            List<Author> author = authorService.Load();
            vm.liBook = liBook;
            vm.liCategory = liCat;
            vm.liAuthor = author;
            return View("BookPage", vm);
        }
        public IActionResult Delete(int id)
        {
            
            BookVM vm = new BookVM();
            vm.book = new Book();
            vm.author = new Author();
            vm.category = new Category();
            List<Book> liBook = bookService.Load();
            List<Category> liCat = categoryService.Load();
            List<Author> author = authorService.Load();
            vm.liBook = liBook;
            vm.liCategory = liCat;
            vm.liAuthor = author;
            bookService.Delete(id);
            return View("BookPage", vm);
        }
    }
}

BookStore1/Controllers/CategoryController.cs
using BookStore1.Data;
using BookStore1.Models;
using BookStore1.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore1.Controllers
{
    public class CategoryController : Controller
    {
        ICategory categoryService;

        public CategoryController(ICategory categoryService)
        {
            this.categoryService = categoryService;
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Index(CategoryVM vm)
        {
            vm.Category = new Category();
            List<Category> cat = categoryService.Load();
            vm.liCategory = cat;
            return View("CategoryPage", vm);
        }
        public IActionResult saveData(CategoryVM vm)
        {
            categoryService.Insert(vm.Category);
            List<Category> cat = categoryService.Load();
            vm.liCategory = cat;
            return View("CategoryPage", vm);
        }

        public IActionResult Search(CategoryVM vm)
        {
            string name = Request.Form["searchCategory"];
            List<Category> licategory = categoryService.LoadCategoryByName(name);
            List<Category> cat = categoryService.Load();
            vm.liCategory = cat;

            vm.liCategory = licategory;
            return View("CategoryPage", vm);
        }

        // I put it in the Ajax Controller because it didn't work properly

        //public IActionResult Edit(int id)
        //{
        //    CategoryVM vm = new CategoryVM();
        //    Category category = categoryService.Load(id);
        //    List<Category> cat = categoryService.Load();
        //    vm.liCategory = cat;
        //    vm.Category = category;
        //    return View("CategoryPage", vm);
        //}
        public IActionResult Update(CategoryVM vm)
        {
            categoryService.Update(vm.Category);
            List<Category> cat = categoryService.Load();
            vm.liCategory = cat;
            return View("CategoryPage", vm);
        }
        public IActionResult DeleteCategory(int id)
        {
            CategoryVM vm = new CategoryVM();
            vm.Category = new Category();
            List<Category> licategory = new List<Category>();
            vm.liCategory = licategory;
            categoryService.Delete(id);
            return View("CategoryPage", vm);
        }
    }
}

BookStore1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStore1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookStore1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BookStore1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BookStore1/Views/Shared/_LayoutPage.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> signInManager

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_LayoutPage</title>
    @*<script src="~/lib/jquery/dist/jquery.js"></script>*@

    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    @*<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>*@

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>

    @*<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>*@



    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    @RenderSection("Head", false)
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <button class="navbar-toggler" type="button" data-target="#navigation"> <span class="navbar-toggler-icon"></span> </button>
        <div class="collapse navbar-collapse">

            <ul class="navbar-nav">
                <li class="nav-item"> <a asp-controller="Book" asp-action="Index" class="nav-link"><img src="~/logoz.PNG" style="width: 93px; margin-top: -13px; height: 54px; " /></a></li>
                @if (signInManager.IsSignedIn(User))
                {
                    <li class="nav-item" style="margin-left: 29px;"><a asp-controller="Book" asp-action="Index" class="nav-link"> Books </a> </li>
                    <li class="nav-item"> <a asp-controller="Author" asp-action="Index" class="nav-link"> Author </a> </li>
                    <li class="nav-item"> <a asp-controller="Category" asp-action="Index" class="nav-link"> Category </a> </li>
                }
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-top: -13px;">
                @if (signInManager.IsSignedIn(User))
                {
                    <li>
                        <a asp-controller="Account" style="margin-left: 686px; color: #FEAD51 " asp-action="Logout"><span class="glyphicon glyphicon-log-out"></span>Logout</a>
                    </li>
                    <li style="color: white; margin-left: 27px;color: #FEAD51 ">@User.Identity.Name</li>
                }
                else
                {
            <li>
                <a asp-controller="Account" asp-action="SignIn" style="margin-left: 918px; color: #FEAD51 "><span class="glyphicon glyphicon-log-in"></span>Sign In</a>
                <a asp-controller="Account" asp-action="Role" style="margin-left: 27px; color: #FEAD51 "><span class="glyphicon glyphicon-log-in"></span>Roles</a>
            </li>
                }
                <li>
                    <a asp-controller="Account" asp-action="Index" style="margin-left: 25px; color: #FEAD51 "><span class="glyphicon glyphicon-user"></span>Sign Up</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="row">
        <div class="col-xs-1 col-lg-1" style="padding-left: 39px;padding-top: 18px;">
            @RenderSection("Body")
        </div>
    </div>

</body>
</html>